<?php

namespace App\Services\Ai;

use App\Services\Contracts\AiServiceInterface;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

use App\Services\DatabaseSchemaService;

class GeminiAiService implements AiServiceInterface
{
    protected ?string $apiKey;
    protected DatabaseSchemaService $schemaService;

    public function __construct(DatabaseSchemaService $schemaService)
    {
        $this->apiKey = config('services.gemini.key');
        $this->schemaService = $schemaService;
    }

    public function generateSql(string $question): AiSqlResponse
    {
        if (empty($this->apiKey)) {
            return new AiSqlResponse(
                success: false,
                error: "Gemini API key is not configured. Please add GEMINI_API_KEY to your .env file."
            );
        }

        $schemaContext = $this->schemaService->getPromptContext();
        $prompt = $this->buildPrompt($question, $schemaContext);

        try {
            $response = Http::timeout(10)
                ->connectTimeout(5)
                ->withHeaders([
                    'Content-Type' => 'application/json',
                ])
                ->post("https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key={$this->apiKey}", [
                    'contents' => [
                        [
                            'parts' => [
                                ['text' => $prompt]
                            ]
                        ]
                    ],
                    'generationConfig' => [
                        'responseMimeType' => 'application/json',
                        'temperature' => 0.1,
                    ]
                ]);

            if ($response->failed()) {
                Log::error('Gemini API call failed', [
                    'status' => $response->status(),
                    'body' => $response->body()
                ]);
                
                $errorMessage = app()->environment('local', 'testing') 
                    ? "Failed to communicate with Gemini API: " . ($response->json('error.message') ?? $response->reason())
                    : "Gemini API gateway error. Please try again later.";

                return new AiSqlResponse(
                    success: false,
                    error: $errorMessage
                );
            }

            $result = $response->json();
            $responseText = $result['candidates'][0]['content']['parts'][0]['text'] ?? '';

            if (empty($responseText)) {
                return new AiSqlResponse(
                    success: false,
                    error: "Empty response received from Gemini API."
                );
            }

            $jsonData = json_decode(trim($responseText), true);

            if (json_last_error() !== JSON_ERROR_NONE || !isset($jsonData['sql'])) {
                Log::error('Failed to parse Gemini response as JSON', ['raw_response' => $responseText]);
                return new AiSqlResponse(
                    success: false,
                    error: "AI returned malformed JSON or missing SQL query."
                );
            }

            return new AiSqlResponse(
                success: true,
                sql: $jsonData['sql'],
                confidence: (float)($jsonData['confidence'] ?? 0.8),
                explanation: $jsonData['explanation'] ?? 'Query generated by Gemini.'
            );

        } catch (\Exception $e) {
            Log::error('Gemini Service Exception', [
                'exception' => $e->getMessage(),
                'trace' => $e->getTraceAsString()
            ]);
            
            $errorMessage = app()->environment('local', 'testing')
                ? "An unexpected error occurred: " . $e->getMessage()
                : "AI SQL translation is temporarily unavailable. Please try again later.";

            return new AiSqlResponse(
                success: false,
                error: $errorMessage
            );
        }
    }



    protected function buildPrompt(string $question, string $schemaContext): string
    {
        return <<<PROMPT
You are a highly secure and accurate SQL generator. Translate the user's natural language question into a single valid MySQL SELECT query based strictly on the provided schema.

Database Schema:
{$schemaContext}

Instructions:
1. You must respond ONLY with a JSON object containing the fields: "sql" (string), "confidence" (float, between 0.0 and 1.0), and "explanation" (string).
2. The generated SQL must be a valid, single SELECT query. Do not execute or generate DDL (CREATE, DROP, ALTER) or DML (INSERT, UPDATE, DELETE).
3. Do not include semicolons at the end of the SQL query.
4. Ensure joins are correct and table aliases are used for clarity.
5. If the question cannot be answered with the given schema, set success: false or provide an appropriate error explanation.

JSON Format:
{
  "sql": "SELECT ...",
  "confidence": 0.95,
  "explanation": "This query joins table A and table B on field X, filters by Y, and calculates the sum of Z."
}

Few-Shot Examples:

Question: "How many customers do we have?"
Response:
{
  "sql": "SELECT COUNT(*) AS total_customers FROM customers",
  "confidence": 0.99,
  "explanation": "Counts the total number of records in the customers table."
}

Question: "What is the total revenue by month?"
Response:
{
  "sql": "SELECT DATE_FORMAT(order_date, '%Y-%m') AS month, SUM(total_amount) AS revenue FROM orders GROUP BY DATE_FORMAT(order_date, '%Y-%m') ORDER BY month ASC",
  "confidence": 0.98,
  "explanation": "Extracts the year and month from order_date, sums the order amounts, and groups chronologically."
}

Question: "Which products have generated the most revenue?"
Response:
{
  "sql": "SELECT p.id, p.name, SUM(oi.total_price) AS total_revenue FROM products p JOIN order_items oi ON p.id = oi.product_id GROUP BY p.id, p.name ORDER BY total_revenue DESC",
  "confidence": 0.97,
  "explanation": "Joins products with order items, aggregates total item price per product, and sorts in descending order."
}

Question: "What is the average order value?"
Response:
{
  "sql": "SELECT AVG(total_amount) AS average_order_value FROM orders",
  "confidence": 0.99,
  "explanation": "Calculates the average total amount across all placed orders."
}

User Question: "{$question}"
PROMPT;
    }
}
